spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:failover://localhost:3306/birdie?autoReconnect=true
    username: birdie
    password: birdie12345

    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: mariadb

management:
  endpoints:
    web:
      exposure:
        include: shutdown, heapdump
  endpoint:
    shutdown:
      enabled: true