spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:failover://localhost:3306/birdie?autoReconnect=true
    username: ENC(Gv1FlgmendTaKGDvOPbRRBcOHVgAX8r8eZcfiun5jm/urJOTwDIJCQQAO2aVOE4V)
    password: ENC(DeYOdPfjDQZiU0m++I+ImJcEYVc3kh19VN5QAxR0QyLKNpxDlkHFCu4hmi0SxD/X)

    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: mariadb

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

jasypt:
  encryptor:
    password: EHHBirdie